name: MacOS SDL2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
      name: Checkout
    - name: Install Packages
      run: |
          set -e
          brew unlink python3
          brew upgrade && brew install --overwrite python3
          brew install cmake make imagemagick
          pip3 install --break-system-packages cogapp generate-iconset
          brew install openal-soft sdl2 sdl2_mixer glew libmodplug libpng
          brew install openssl@3 protobuf
    - name: cmake
      run: export HOMEBREW_PREFIX="/usr/local" && ./.github/build_macos.sh
